import {
  LogIn,
  LayoutDashboard,
  Briefcase,
  FolderOpen,
  Upload,
  AlertTriangle,
  CheckCircle,
  ClipboardList,
  FileCheck,
  Shield,
  ShieldCheck,
  Activity,
  TrendingUp,
  Target,
  BarChart3,
  Settings,
  Bell,
  Code,
  History,
  KeyRound,
  Rocket,
  Workflow,
  Users,
  Sparkles,
  HelpCircle,
  BookOpen,
  type LucideIcon,
} from 'lucide-react'

const ICONS: Record<string, LucideIcon> = {
  LogIn,
  LayoutDashboard,
  Briefcase,
  FolderOpen,
  Upload,
  AlertTriangle,
  CheckCircle,
  ClipboardList,
  FileCheck,
  Shield,
  ShieldCheck,
  Activity,
  TrendingUp,
  Target,
  BarChart3,
  Settings,
  Bell,
  Code,
  History,
  KeyRound,
  Rocket,
  Workflow,
  Users,
  Sparkles,
  HelpCircle,
  BookOpen,
}

/** Resolve a stored icon-name string to a lucide component (falls back to HelpCircle). */
export function resolveIcon(name?: string): LucideIcon {
  if (name && ICONS[name]) return ICONS[name]
  return HelpCircle
}
